version: '2'

services:
  databasee:
    image: mysql
    container_name: databasea
    environment:
      - MYSQL_ROOT_PASSWORD=testing
      - MYSQL_DATABASE=django
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=testing
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"

  app:
    build: .
    container_name: djangolatse
    links:
      - databasee
    ports: 
      - "8000:8000"
    command: ./start.sh
  
    depends_on:
      - databasee

